### ISSUE TITLE
Confused by the newer version

### ISSUE THREAD

**Issue by nestsman** [Nilhcem/FakeSMTP#27]
I got version 1.13 from this website:

https://nilhcem.github.io/FakeSMTP/download.html

Then I realized there was a newer version here on Git, so I downloaded that one.  However, the newer version doesn't seem to have a .jar file in all the directories I looked in.  How come that last version was a simple .jar file download that ran beautifully when I clicked on it, and this version is not so simple?

Please advise.

Thank you.

**Comment by Nilhcem** [comment]
Latest version is the one you can download directly from the website (1.13)
Version 1.14 on Git is a development version, not the latest release.
If you want to build your own version from the GitHub sources, you can run the following:

```bash
git clone git@github.com:Nilhcem/FakeSMTP.git
cd FakeSMTP
mvn package -Dmaven.test.skip
```
Generated jar file will be located in `./target/fakeSMTP-1.14-SNAPSHOT.jar`
