### ISSUE TITLE
Allow binding to specific interface in GUI mode

### ISSUE THREAD

**Issue by phansson** [Nilhcem/FakeSMTP#32]
Would like to see the option to bind to a specific network interface (`-a` option) to be valid generally. There's no good reason why this option should only be valid in non-GUI mode.

**Comment by Vest** [comment]
@phansson, I have created the pull request.
If you have time, feel free to test my implementation before @Nilhcem reviews it.

Thanks.

**Comment by Nilhcem** [comment]
@phansson, @Vest,
Many thanks, 
This has been merged and will be available when version 2.1 is published
